# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - ci/cd
    reviewers:
      - authorhealth/backend
      - authorhealth/infrastructure
    schedule:
      # Check for updates to GitHub Actions every week
      interval: weekly
      day: tuesday
      time: "12:00"

  - package-ecosystem: gomod
    directories:
      - /
      - /cli
    groups:
      golang-org-x:
        patterns:
          - "golang.org/x/*"
      otel:
        patterns:
          - "go.opentelemetry.io/otel"
          - "go.opentelemetry.io/otel/*"
          - "go.opentelemetry.io/contrib/*"
    labels:
      - dependencies
      - go
    reviewers:
      - authorhealth/backend
    schedule:
      interval: weekly
      day: wednesday
      time: "17:00"
